### ISSUE TITLE
Please Review trace

### ISSUE THREAD

**Issue by dewittpe** [aljensen89/CommKern#17]
@aljensen89 

I added a file R/utilities.R were I defined the trace function for a square matrix.  I did this to avoid having to import the psych package.  To the best of my knowledge the `psych::tr` was the only function used from psych.  The reimplementation of the trace function within CommKern makes it just a little bit easier to maintain as there is one less package to import.

I had to resolve a merge conflict in the four R/score_*.R files.  Please verify that the correct test statistics are being calculated in each of the files.

**Comment by aljensen89** [comment]
All of the score functions look good based on my review. I have added the full Liu et al. (2008) reference in each function's @reference section
