### ISSUE TITLE
No examples

### ISSUE THREAD

**Issue by dewittpe** [aljensen89/CommKern#4]
There are no examples in the documentation.   Some examples will need to be provided if this package is to accepted on CRAN.

Methods that need examples:

- [x] community_plot
- [x] compute_mod_matrix
- [ ] compute_multimodal_mod
- [ ] #12
- [ ] degree
- [ ] find_start_temp
- [ ] heatbath_multimodal
- [x] hms (hier_mult_spin)
- [x] matrix_to_df
- [ ] subset_matrix_to_df

**Comment by aljensen89** [comment]
Added examples to end-user facing functions. Some of these functions won't be available for the end user to see, so I won't add examples to them.
